# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
#########################################################################
############ BUILD ######################################################
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 01 Docker Build image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'marksxp/servicenet5'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: CopyFiles@2
      displayName: 02 CopyFiles
      inputs:
        Contents: '**/*.yml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 03 PublishBuildArtifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

#########################################################################
############ DEPLOY #####################################################
- stage: Deploy
  displayName: Build
  jobs:
  - job: Deploy
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 01 DownloadPipelineArtifact
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        itemPattern: '**/*.yml'
        targetPath: '$(System.ArtifactsDirectory)'
    - task: KubernetesManifest@0
      displayName: 02 KubernetesManifest
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'kube-cluster-connection1'
        manifests: '$(System.ArtifactsDirectory)/k8s.yml'
        containers: 'marksxp/servicenet5:$(tag)'
    